spring.application.name=backend

# Railway fournit le port via la variable d'environnement PORT
server.port=${PORT:8080}  
server.address=0.0.0.0

# Connexion à la DB
# Railway fournit souvent l'URL complète en DATABASE_URL, mais si tu as déjà hosté une DB, garde ça
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:app_db}
spring.datasource.username=${DB_USERNAME:app_user}
spring.datasource.password=${DB_PASSWORD:app_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pour supporter les ENUMs PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jwt configuration
jwt.secret=${JWT_SECRET:KJH87f98sd76FSD7f8sd!@#DebateArena#123kldjsf98DSF7}
jwt.expiration-ms=900000

# Logging
logging.level.root=info
